// Generated by package-kling-sleep.mjs; full-frame, fixed-camera artwork.
export const SLEEP_ART_VERSION = "sleep-bed-v2";
export const SLEEP_SHEETS = {
  "enter": {
    "columns": 4,
    "tileWidth": 480,
    "tileHeight": 480,
    "pageFrames": 24,
    "frames": 193,
    "pages": [
      {
        "src": "/assistant/chibi-sleep-enter-v2-0.webp",
        "sha256": "3994da9a03dd28d1c349a2149dd20f56ffbc4d7b647f2cb894aea2fbaa85d45e",
        "bytes": 520566,
        "width": 1920,
        "height": 2880,
        "start": 0,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-1.webp",
        "sha256": "7f659afe56a65aa560b8e34fef73b7fc6006b4cc78573e32a82b82bd198962cc",
        "bytes": 512376,
        "width": 1920,
        "height": 2880,
        "start": 24,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-2.webp",
        "sha256": "256f6515500eabe221f79a5e23d6ecf8bfcad1fd150e3058d0e4e98ebc169e41",
        "bytes": 496814,
        "width": 1920,
        "height": 2880,
        "start": 48,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-3.webp",
        "sha256": "ddebcd673c4499b59676d4dfcda623eac7e8fbc65a367af030fc7a7ac3b41bca",
        "bytes": 538382,
        "width": 1920,
        "height": 2880,
        "start": 72,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-4.webp",
        "sha256": "6170d0b6eb65a0b1d2f8a473281593f2f32a3413c24b6d19ed82530e96411b9e",
        "bytes": 567260,
        "width": 1920,
        "height": 2880,
        "start": 96,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-5.webp",
        "sha256": "820d1e634c73d0eb8e983cd09457444c4681435abe7648f18aed4ef39e0662f6",
        "bytes": 515408,
        "width": 1920,
        "height": 2880,
        "start": 120,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-6.webp",
        "sha256": "13b678ea44a1e4af839a9578c074a8f25124398a86d9cee59f569ca2ce822db0",
        "bytes": 476896,
        "width": 1920,
        "height": 2880,
        "start": 144,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-7.webp",
        "sha256": "acea75fd13598572835d08f45daed4d90e121faf58f0bbded8cd1fcb9f478e88",
        "bytes": 474738,
        "width": 1920,
        "height": 2880,
        "start": 168,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-enter-v2-8.webp",
        "sha256": "e950affd3578e44cb965d4ceadba7fb6940e9ecf18f7666e4218f77dad1e2c09",
        "bytes": 23288,
        "width": 1920,
        "height": 480,
        "start": 192,
        "frames": 1
      }
    ]
  },
  "wake": {
    "columns": 4,
    "tileWidth": 480,
    "tileHeight": 480,
    "pageFrames": 24,
    "frames": 121,
    "pages": [
      {
        "src": "/assistant/chibi-sleep-wake-v2-0.webp",
        "sha256": "2054957ac54dad5e01889ed074a7711f707a1f3e6d7a9b0561901eca83de3016",
        "bytes": 511830,
        "width": 1920,
        "height": 2880,
        "start": 0,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-wake-v2-1.webp",
        "sha256": "aa98be06aaebde0cbe0cbf5b46bb9758aa09480f2e73750805ecf7779a279c46",
        "bytes": 541698,
        "width": 1920,
        "height": 2880,
        "start": 24,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-wake-v2-2.webp",
        "sha256": "b984a309b5296f4b5639693c7f211c991dfc34488df7ed99396138ec3191fdb0",
        "bytes": 586878,
        "width": 1920,
        "height": 2880,
        "start": 48,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-wake-v2-3.webp",
        "sha256": "255680c016a802e7276d8cd2dea3b07f60b209d7e4b2155f8813193d982c745e",
        "bytes": 564762,
        "width": 1920,
        "height": 2880,
        "start": 72,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-wake-v2-4.webp",
        "sha256": "efb7b2106989de0412906fcf47adcfecad5a1c92dea9d90b593a5aa5191e6f79",
        "bytes": 427524,
        "width": 1920,
        "height": 2880,
        "start": 96,
        "frames": 24
      },
      {
        "src": "/assistant/chibi-sleep-wake-v2-5.webp",
        "sha256": "17d382712cd9987680854065aafe63a8e80de3ae6acc884f7e94b80144f9a6f3",
        "bytes": 20748,
        "width": 1920,
        "height": 480,
        "start": 120,
        "frames": 1
      }
    ]
  }
} as const;
export const SLEEP_LOOP = [192,191,190,189,188,187,186,185,184,183,182,181,180,179,178,177,176,175,174,173,172,171,170,169,168,167,166,165,164,163,162,161,160,159,158,157,156,155,154,153,152,151,150,149,148,147,146,145,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191] as const;
export const SLEEP_FPS = 24;
